
    create table place (
       id bigint generated by default as identity,
        city varchar(255),
        created_at timestamp,
        name varchar(255),
        slug varchar(255),
        state varchar(255),
        updated_at timestamp,
        primary key (id)
    );

    create table placedto (
       id bigint generated by default as identity,
        city varchar(255),
        name varchar(255),
        slug varchar(255),
        state varchar(255),
        primary key (id)
    );
